spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/web
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT
app.jwt.secret=f132be662a9b4b867b597452569eceb622523ae40b18aa70ac8ac94513a5efdf
app.jwt.expiration=86400000

app.frontend.url=http://localhost:5173

# Cookie
app.cookie.access-token-name=access_token
app.cookie.secure=true